INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('1', '40', '155.8');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('2', '50', '178.2');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('3', '55', '187.1');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('4', '60', '195.8');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('5', '61', '197.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('6', '62', '199.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('7', '63', '201.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('8', '64', '203.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('9', '65.05', '205.6');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('10', '66', '207.2');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('11', '67', '209.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('12', '68', '211.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('13', '69', '213.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('14', '70.05', '215.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('15', '71', '217.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('16', '72', '219.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('17', '73', '221.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('18', '74', '223.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('19', '75', '225.9');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('20', '76', '228.1');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('21', '77', '230.3');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('22', '78', '232.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('23', '79', '235.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('24', '80', '237.8');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('25', '81', '240.3');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('26', '82', '242.9');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('27', '83', '245.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('28', '84', '248.3');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('29', '85', '251.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('30', '86', '254.2');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('31', '87', '257.3');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('32', '88', '260.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('33', '89', '264.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('34', '90', '268.7');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('35', '91', '272.9');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('36', '92', '277.8');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('37', '93', '282.8');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('38', '94', '288.5');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('39', '95', '295.2');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('40', '96', '303.6');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('41', '97', '313.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('42', '98', '327.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('43', '98.5', '335.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('44', '99', '346');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('45', '99.5', '361.1');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('46', '99.7', '373.3');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('47', '99.8', '381.6');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('48', '99.9', '393.4');
INSERT INTO "main"."wa_atar" ("id", "atar", "min_tea") VALUES ('49', '99.95', '402.5');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('1', 'Accounting and Finance', '58', '11.5', '93.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('2', 'Ancient History', '64.9', '35.9', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('3', 'Animal Production Systems', '50.3', '23.7', '73.2');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('4', 'Applied Information Technology', '53.6', '7.1', '89.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('5', 'Arabic', '57', '13.6', '87.4');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('6', 'Auslan', '67.5', '53.8', '79');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('7', 'Aviation', '55.7', '26.2', '72.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('8', 'Biology', '57.6', '8.8', '95.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('9', 'Business Management and Enterprise', '54.2', '7', '92.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('10', 'Career and Enterprise', '56', '17.4', '94.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('11', 'Chemistry', '63.2', '13.9', '99.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('12', 'Children; Family and the Community', '60.1', '37.4', '89.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('13', 'Chinese: Background Language', '61.4', '40.3', '71.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('14', 'Chinese: First Language', '48.3', '0', '90.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('15', 'Chinese: Second Language', '70.7', '40.7', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('16', 'Computer Science', '57', '17.2', '92.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('17', 'Croatian', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('18', 'Dance', '56.6', '15.8', '93.2');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('19', 'Design', '55.9', '15.8', '92.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('20', 'Drama', '55.2', '5.2', '96.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('21', 'Dutch', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('22', 'Earth and Environmental Science', '55.4', '19.8', '88.4');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('23', 'Economics', '59.9', '12.6', '96.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('24', 'Engineering Studies', '56.8', '22', '91.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('25', 'English', '57.3', '5.1', '93.8');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('26', 'English as an Additional Language or Dialect', '55.4', '1', '94');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('27', 'Filipino', '59.1', '40.1', '72.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('28', 'Food Science and Technology', '57.8', '25.2', '90.2');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('29', 'French: Background Language', '60.9', '41.3', '73.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('30', 'French: Second Language', '69', '30.1', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('31', 'Geography', '55.2', '9.4', '91.8');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('32', 'German: Background Language', '62.7', '46.3', '85.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('33', 'German: Second Language', '68', '42.4', '88.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('34', 'Health Studies', '53', '8.1', '89.4');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('35', 'Hebrew', '59.4', '56.3', '67.5');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('36', 'Hindi', '56.5', '30.5', '95.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('37', 'Human Biology', '58.6', '9.7', '94.5');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('38', 'Hungarian', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('39', 'Indonesian: First Language', '57.9', '53', '66.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('40', 'Indonesian: Second Language', '63', '26', '90.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('41', 'Integrated Science', '45.5', '11.1', '85');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('42', 'Italian: Background Language', '69.9', '45.5', '90');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('43', 'Italian: Second Language', '63.5', '25.3', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('44', 'Japanese: Background Language', '56.8', '25.9', '76.2');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('45', 'Japanese: Second Language', '65.5', '28.1', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('46', 'Karen', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('47', 'Korean: Background Language', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('48', 'Literature', '66', '18.2', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('49', 'Macedonian', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('50', 'Malay: Background Speakers', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('51', 'Marine and Maritime Studies', '55', '19.3', '91.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('52', 'Materials Design and Technology', '55.2', '26.5', '91.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('53', 'Mathematics Applications', '54.7', '2.6', '91');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('54', 'Mathematics Methods', '64.6', '12.5', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('55', 'Mathematics Specialist', '68.2', '16.1', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('56', 'Media Production and Analysis', '55.4', '10.2', '93');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('57', 'Modern Greek', '73.2', '60.1', '85.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('58', 'Modern History', '57.9', '3.5', '96.3');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('59', 'Music', '62.5', '16.1', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('60', 'Outdoor Education', '52.6', '17.7', '87.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('61', 'Persian', '56.5', '36.2', '72.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('62', 'Philosophy and Ethics', '63.1', '25.6', '100');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('63', 'Physical Education Studies', '54.8', '8', '92.2');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('64', 'Physics', '62.5', '9.4', '98.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('65', 'Plant Production Systems', '49.5', '21', '73.6');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('66', 'Polish', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('67', 'Politics and Law', '62', '16.6', '97.9');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('68', 'Portuguese', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('69', 'Psychology', '56.9', '10.5', '92.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('70', 'Punjabi', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('71', 'Religion and Life', '60.7', '19.5', '93.1');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('72', 'Romanian', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('73', 'Russian', '66.5', '45.2', '79');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('74', 'Serbian', '55', '23.8', '78.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('75', 'Sinhala', '57.6', '38.2', '71.8');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('76', 'Spanish', '66.2', '42.7', '87.8');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('77', 'Swedish', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('78', 'Tamil', '62.2', '48.7', '74.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('79', 'Turkish', '0', '0', '0');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('80', 'Vietnamese', '67.3', '43.4', '80.7');
INSERT INTO "main"."wa_scaling" ("id", "course", "mean", "min_mark", "max_mark") VALUES ('81', 'Visual Arts', '57.2', '10.7', '94.7');