# Generated by Django 5.0.1 on 2024-02-02 00:28

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicantionid', models.IntegerField(verbose_name='application_id')),
                ('atar', models.IntegerField(verbose_name='atar')),
                ('regionid', models.IntegerField(verbose_name='region_id')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('note', models.CharField(max_length=500, null=True, verbose_name='note')),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'application_student',
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('label', models.CharField(max_length=255, unique=True, verbose_name='label')),
            ],
            options={
                'db_table': 'grade_type',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nsw_atar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'nsw_atar',
            },
        ),
        migrations.CreateModel(
            name='Nsw_scaling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
                ('number', models.IntegerField(null=True)),
                ('type_of_mark', models.CharField(max_length=20)),
                ('mean', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('sd', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('max_mark', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('p99', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('p90', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('p75', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('p50', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('p25', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'nsw_scaling',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='region_name')),
                ('abbreviation', models.CharField(max_length=255, verbose_name='abbr')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Sa_atar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aggregate', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'sa_atar',
            },
        ),
        migrations.CreateModel(
            name='Tas_atar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tes', models.IntegerField(null=True)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'tas_atar',
            },
        ),
        migrations.CreateModel(
            name='Tas_scaling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('course', models.CharField(max_length=255, verbose_name='course')),
                ('nnpa_n', models.IntegerField(verbose_name='nn/pa_n')),
                ('sa_min', models.IntegerField(verbose_name='sa_min')),
                ('sa_max', models.IntegerField(verbose_name='sa_max')),
                ('sa_n', models.IntegerField(verbose_name='sa_n')),
                ('ca_min', models.IntegerField(verbose_name='ca_min')),
                ('ca_max', models.IntegerField(verbose_name='ca_max')),
                ('ca_n', models.IntegerField(verbose_name='ca_n')),
                ('ha_min', models.IntegerField(verbose_name='ha_min')),
                ('ha_max', models.IntegerField(verbose_name='ha_max')),
                ('ha_n', models.IntegerField(verbose_name='ha_n')),
                ('ea_min', models.IntegerField(verbose_name='ea_min')),
                ('ea_max', models.IntegerField(verbose_name='ea_max')),
                ('ea_n', models.IntegerField(verbose_name='ea_n')),
            ],
            options={
                'db_table': 'tas_scaling',
            },
        ),
        migrations.CreateModel(
            name='Tas_scaling_alt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('sa_min', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('sa_max', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ca_min', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ca_max', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ha_min', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ha_max', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ea_min', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('ea_max', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'tas_scaling_alt',
            },
        ),
        migrations.CreateModel(
            name='Tas_subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tas_subject',
            },
        ),
        migrations.CreateModel(
            name='Vic_atar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('range_low', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('range_high', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vic_atar',
            },
        ),
        migrations.CreateModel(
            name='Vic_scaling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('study_code', models.CharField(max_length=10)),
                ('study_name', models.CharField(max_length=50)),
                ('mean', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sd', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_20', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_25', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_30', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_35', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_40', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_45', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('scaled_score_50', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'vic_scaling',
            },
        ),
        migrations.CreateModel(
            name='Wa_atar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('min_tea', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'wa_atar',
            },
        ),
        migrations.CreateModel(
            name='Wa_scaling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
                ('mean', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('min_mark', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('max_mark', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'wa_scaling',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['c_time'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('units', models.CharField(max_length=255, verbose_name='unit')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('is_language', models.BooleanField(default=None, null=True)),
                ('regionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='BasicSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('regionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'basic_subject',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=255)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicationstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'application_student_subject',
                'unique_together': {('application_student', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='subjects',
            field=models.ManyToManyField(through='core.ApplicationStudentSubject', to='core.subject'),
        ),
    ]
